# This workflow configures the user-statistician to
# generate only the language distribution chart, using
# the dark color theme. It is configured on a daily 
# schedule at 3am.

name: user-statistician

on:
  #schedule:
    #- cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/languages.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        language-repository-exclusions: databases_1_2_sql_uniwa
        colors: dark
        hide-keys: general, contributions, repositories
        include-title: true
        custom-title: 'Most Used Languages'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
